### ISSUE TITLE
Error when using module

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos-ipv4#2]
TASK [arista.eos-ipv4 : Gather EOS configuration] ******************************
task path: /private/etc/ansible/roles/arista.eos-ipv4/tasks/main.yml:3
<spine1> ESTABLISH LOCAL CONNECTION FOR USER: sean
<spine1> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1461688512.98-217685172499040`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1461688512.98-217685172499040`" )'
<spine1> PUT /var/folders/3q/q76fdfsd043dzhmcjldlqpjr0000gn/T/tmpUVRdQV TO /Users/sean/.ansible/tmp/ansible-tmp-1461688512.98-217685172499040/eos_command
<spine1> EXEC /bin/sh -c 'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /Library/Frameworks/Python.framework/Versions/2.7/bin/python /Users/sean/.ansible/tmp/ansible-tmp-1461688512.98-217685172499040/eos_command; rm -rf "/Users/sean/.ansible/tmp/ansible-tmp-1461688512.98-217685172499040/" > /dev/null 2>&1'
...

TASK [arista.eos-ipv4 : set_fact] **********************************************
task path: /private/etc/ansible/roles/arista.eos-ipv4/tasks/main.yml:17
fatal: [spine1]: FAILED! =>*\* {"failed": true, "msg": "'dict object' has no attribute 'result'"}**

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @spine.retry

PLAY RECAP *********************************************************************
spine1                     : ok=6    changed=0    unreachable=0    failed=1   

The gather_facts section seems to be different than other modules. eos-ipv4 uses:
- name: Gather EOS configuration
  eos_command:
  ...
  register: output
- set_fact:
  base_config='{{ output.result[0] }}'

eos-interfaces and others use:
- name: Gather EOS configuration
  eos_command:
  ...
  register: output
  no_log: "{{ no_log|default(true) }}"
  when: _eos_config is not defined
- name: Save EOS configuration
  set_fact:
    _eos_config: "{{ output.stdout[0] }}"
  no_log: "{{ no_log|default(true) }}"
  when: _eos_config is not defined

**Comment by grybak-arista** [comment]
Thanks for pointing out the issue. The fix is in process, should be pushed to ansible-galaxy soon.
